### ISSUE TITLE
EPSolar Dashboard Error

### ISSUE THREAD

**Issue by kasper58** [AdamWelchUK/NodeRedEPEverDashboard#10]
Hi Adam, 
Ran into a problem with installing your Dashboard into Node-Red. 
Import into clipboard gives an "ERROR: Input not a JSON Array."
See attached screenshot.
![image](https://user-images.githubusercontent.com/34113487/133532500-3892c688-d8f8-4d7a-b654-f42329e68835.png)

Regards Warren

**Comment by kasper58** [comment]
Duh..... Sorted thanks
The file... not the filename.

**Comment by kasper58** [comment]
- [ ] Duh..... Sorted thanks
The file... not the filename.

**Comment by dtabone** [comment]
Kasper58 See this post too.. https://github.com/AdamWelchUK/NodeRedEPEverDashboard/issues/8#issuecomment-868697479

**Comment by kasper58** [comment]
Thanks Adam.
I saw that and are trying to use it as a basis for my EPEver Charger /
Inverter. Having some issues getting RS458 to connect.
I have the protocol  sheet (att) but nobody is at home.

Regards Warren
