### ISSUE TITLE
Flow not working

### ISSUE THREAD

**Issue by kingfash** [AdamWelchUK/NodeRedEPEverDashboard#19]
Hi @AdamWelchUK ,

Thanks for the great work. 

Please I need help to get the flow to work. I'm using the original Epever USB to RS485 cable. I have installed the cable driver and set the Modbus Get but the flows seems not working.  I have previous used your EPEverDashboardv0.1.json with my old Raspberry Pi with same cable but can't find the old .json code again to try. Please I need help. 

Thank you.

Femi

PS:
I'm not a programmer but can follow instruction to get things work.

Attached is the screenshot of my setting.
![node-red-flow](https://user-images.githubusercontent.com/17705741/159576966-f29260f8-330b-4eec-91f1-cc83eda3b2ea.JPG)

![xrusb0](https://user-images.githubusercontent.com/17705741/159577073-52b78902-242b-4bd6-8d46-def0347e8f12.JPG)

**Comment by kedar-1** [comment]
Try to run a Python code to verify the driver/cable is working as expected.

**Comment by kingfash** [comment]
Hello @kedar-1,

Thank you for your reply. Kindly help with sample Python code to test.

Thank you.

**Comment by kingfash** [comment]
It's working fine now. I have to remove the driver and reinstall afresh.
Thanks.
